# Directory and file filters

included:
  - EntainTechTest

excluded:
  - EntainTechTestTests
  - EntainTechTestUITests

# Enabled/disabled rules
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - all
disabled_rules:
  - anonymous_argument_in_multiline_closure
  - async_without_await
  - attributes
  - closure_body_length
  - conditional_returns_on_newline
  - contrasted_opening_brace
  - convenience_type
  - discouraged_optional_collection
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - file_types_order
  - function_default_parameter_at_end
  - indentation_width
  - let_var_whitespace
  - missing_docs
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_parameters_brackets
  - no_extension_access_modifier
  - no_grouping_extension
  - no_magic_numbers
  - one_declaration_per_file
  - operator_usage_whitespace
  - prefer_key_path # Re-enable once we are on Swift 6.
  - prefer_nimble
  - prefer_self_in_static_references
  - prefixed_toplevel_constant
  - required_deinit
  - shorthand_optional_binding
  - shorthand_argument
  - sorted_enum_cases
  - strict_fileprivate
  - superfluous_else
  - switch_case_on_newline
  - todo
  - trailing_closure
  - type_contents_order
  - vertical_whitespace_between_cases

force_unwrapping: 
  severity: error 
line_length: 150
